name: null
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - jupyter
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - openpyxl=3.1.0  # .xlsx new office
  - xlrd  # .xls old office 2003
  - wordcloud
  - folium
  - scipy
  - scikit-learn
